fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        entry: black
        require_serial: true
        types: [ python ]

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
        exclude: '__init__.py'

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.236'
    hooks:
      - id: ruff
        name: ruff
        stages: [ commit ]
        types: [ file, python ]
        args: ["--fix"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        name: django-upgrade
        stages: [commit]
        args: [--target-version, "4.0"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]
